# The inputs that influenced $d_{ij}$.
# Input: $d_{ij}$ - single element

import pymongo
#from pyspark.sql import SparkSession
import pandas as pd
import pprint


def get_why_prov(relations, entities, ents_id):
	# Get input entities from ents_id:
	input_entities = entities.find({'identifier':{'$in': ents_id}, 'attributes.instance':'-1'},{'identifier':1,'_id':0}).distinct('identifier')
	
	# Select intermediate entities:
	diff = lambda l1, l2: [x for x in l1 if x not in l2]
	ents_id = diff(ents_id, input_entities)

	# Find the activities that generated the intermediate entities:
	acts = []
	generated_act = relations.find({'prov:entity': {'$in':ents_id}, 'prov:relation_type':'wasGeneratedBy'})
	for act in generated_act:
		act_id = act['prov:activity']
		if act_id not in acts:
			acts.append(act_id)

	if not acts:
		# Base case: entities is not generated by any activity
		return input_entities
	else:
		# Find the entities used by the activities:
		ents = []
		used_ent = relations.find({'prov:activity':{'$in':acts}, 'prov:relation_type':'used'})
		for ent in used_ent:
			ent_id = ent['prov:entity']
			if ent_id not in ents:
				ents.append(ent_id)

		return input_entities + get_why_prov(relations, entities, ents)
	

if __name__ == "__main__":

	# Connect with MongoClient on the default host and port:
	client = pymongo.MongoClient('localhost', 27017)

	# Getting a Database:
	db = client['german_prov']

	# Get entities and relations mongodb collection:
	entities = db.entities
	relations = db.relations

	# Element identifier $d_{ij}$:
	entity_id = 'entity:0d69c672-d521-498e-aa94-7773f634fb39'

	# Get identifier list of input entities that influenced an element:
	ents = get_why_prov(relations, entities, [entity_id])

	# Find mongodb documents from identifier list:
	#why_prov = entities.find({'identifier':{'$in':ents}})
	db.why_prov.drop()
	why_prov = entities.aggregate([{'$match':{'identifier':{'$in':ents}}}, {'$out':'why_prov'}])

	# Print description of input entities that influenced the element $d_{ij}$:
	#print(why_prov.explain())
	print('Result saved in why_prov collection.')




